# This file was generated by GoReleaser. DO NOT EDIT.
cask "ghaperf" do
  name "ghaperf"
  desc "ghaperf is a CLI to analyze the performance of GitHub Actions using GitHub API and raw job logs"
  homepage "https://github.com/suzuki-shunsuke/ghaperf"
  version "0.0.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ghaperf"

  on_macos do
    on_arm do
      url "https://github.com/suzuki-shunsuke/ghaperf/releases/download/v#{version}/ghaperf_darwin_arm64.tar.gz"
      sha256 "ddb2ca344d39ab9df9ef4720480418f34c3766dafa644cb92679ebc1f14e7794"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/suzuki-shunsuke/ghaperf/releases/download/v#{version}/ghaperf_linux_amd64.tar.gz"
      sha256 "d6256babdf85b9822e15d5fb296b1ef7989f528cd3dc1e24841d7b473dcdb222"
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/ghaperf/releases/download/v#{version}/ghaperf_linux_arm64.tar.gz"
      sha256 "4ee8016af5d56fb3cf288fb7be1b9e103400e0126141db7f73d1e70222c3fd05"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ghaperf"]
    end
  end

  # No zap stanza required
end
