# This file was generated by GoReleaser. DO NOT EDIT.
cask "ghaperf" do
  name "ghaperf"
  desc "ghaperf is a CLI to analyze the performance of GitHub Actions using GitHub API and raw job logs"
  homepage "https://github.com/suzuki-shunsuke/ghaperf"
  version "0.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ghaperf"

  on_macos do
    on_arm do
      url "https://github.com/suzuki-shunsuke/ghaperf/releases/download/v#{version}/ghaperf_darwin_arm64.tar.gz"
      sha256 "78ae754e807d599bf88186e1a8d0ef8efae6a182fbcddc5163498e630568c908"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/suzuki-shunsuke/ghaperf/releases/download/v#{version}/ghaperf_linux_amd64.tar.gz"
      sha256 "aa0ef5f05ba112b98412bbab052341ab76e4f08d1b1ce2ab43e28b1d009ca1dc"
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/ghaperf/releases/download/v#{version}/ghaperf_linux_arm64.tar.gz"
      sha256 "5d254ae7f298add46ee7fd6ec8e25acfdd3c5a4c70a45d9f2012435717e22101"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ghaperf"]
    end
  end

  # No zap stanza required
end
