# This file was generated by GoReleaser. DO NOT EDIT.
cask "ghaperf" do
  version "1.0.1"

  on_macos do
    on_arm do
      sha256 "dc62de42f73a88cb102dfbe41eadd3c53391a22a6bd7769332d5e2a3b66f2697"
      url "https://github.com/suzuki-shunsuke/ghaperf/releases/download/v#{version}/ghaperf_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7f4199786b064ccf88a67e5319797411158dfa43eff9b95d253c240c16996ba0"
      url "https://github.com/suzuki-shunsuke/ghaperf/releases/download/v#{version}/ghaperf_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "1d4609ffc93a95a9d7f13af8e3181a4118081d1e9fb60a0f81fd24d3ee33d0db"
      url "https://github.com/suzuki-shunsuke/ghaperf/releases/download/v#{version}/ghaperf_linux_arm64.tar.gz"
    end
  end

  name "ghaperf"
  desc "ghaperf is a CLI to analyze the performance of GitHub Actions using GitHub API and raw job logs"
  homepage "https://github.com/suzuki-shunsuke/ghaperf"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ghaperf"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ghaperf"]
    end
  end

  # No zap stanza required

end
